#!/usr/bin/python3

import optparse
import socket
import sys

waiting = True
waitfor = "*"
errno = 0

op = optparse.OptionParser(usage="usage: %prog [-h] [-v] [-p|-r|-c jobid]")
op.add_option("-v", "--verbose",
              action="store_true", default=False,
              help="don't show incomming data")
op.add_option("-p", "--pending",
              action="store", type="string", default="", metavar="jobid",
              help="wait until jobid is pending")
op.add_option("-r", "--running",
              action="store", type="string", default="", metavar="jobid",
              help="wait until jobid is pending")
op.add_option("-c", "--complete",
              action="store", type="string", default="", metavar="jobid",
              help="wait until jobid is pending")
op.add_option("-H", "--host",
              action="store", type="string", default="localhost", metavar="hostname",
              help="hostname to connect to (Default: localhost)")
op.add_option("-P", "--port",
              action="store", type="int", default=50007, metavar="port",
              help="port to connect to (Default: 50007)")
(opts, args) = op.parse_args()

if opts.pending != "":
  waitfor = " %s pending" % (opts.pending)
if opts.running != "":
  waitfor = " %s running" % (opts.running)
if opts.complete != "":
  waitfor = " %s complete" % (opts.complete)

# Check that user actually wants to do something.
if waitfor == "*" and not opts.verbose:
  print("Refusing to silently waiting for nothing.")
  sys.exit()

# Create a socket (SOCK_STREAM means a TCP socket)
sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)

try:
  # Connect to server
  sock.connect((opts.host, opts.port))
except :
  print("Error connecting.")
  sys.exit(1)

#    sock.sendall(data + "\n")

while waiting:
  # Receive data from the server and shut down
  received = str(sock.recv(1024), "ascii").strip()
  if received == "":
    errno = 1
    waiting = False
  else:
    if opts.verbose:
      print(received)
    # Check it match and exit
    if waitfor in received:
      if not opts.verbose:
        print(received)
      waiting = False

sock.close()
sys.exit(errno)
